const express = require('express');
const multer = require('multer');
const { Server } = require('socket.io');
const http = require('http');
const { v4: uuidv4 } = require('uuid');
const admZip = require('adm-zip');
const { spawn } = require('child_process');
const fs = require('fs');
const path = require('path');
const cors = require('cors');

const app = express();
const server = http.createServer(app);
const io = new Server(server, {
  cors: {
    origin: '*',
  }
});

app.use(cors());

// Configure multer for file uploads
const upload = multer({ dest: 'uploads/temp/' });

// Ensure uploads directory exists
const uploadsDir = path.join(__dirname, 'uploads');
if (!fs.existsSync(uploadsDir)) {
  fs.mkdirSync(uploadsDir, { recursive: true });
}

// Socket.io for log streaming
io.on('connection', (socket) => {
  console.log('Client connected:', socket.id);

  socket.on('join_build', (buildId) => {
    socket.join(buildId);
    console.log(`Socket ${socket.id} joined build room ${buildId}`);
  });

  socket.on('disconnect', () => {
    console.log('Client disconnected:', socket.id);
  });
});

app.post('/build', upload.single('project'), async (req, res) => {
  try {
    if (!req.file) {
      return res.status(400).json({ error: 'No project file uploaded' });
    }

    const buildType = req.body.buildType || 'dev'; // 'dev' or 'prod'
    const buildId = uuidv4();
    const buildDir = path.join(__dirname, 'uploads', buildId);
    
    // Create build directory
    fs.mkdirSync(buildDir, { recursive: true });

    // Unzip the uploaded file
    const zipPath = req.file.path;
    const zip = new admZip(zipPath);
    zip.extractAllTo(buildDir, true);
    
    // Cleanup the uploaded zip
    fs.unlinkSync(zipPath);

    // Respond to the client with the buildId so they can connect to sockets
    res.json({ buildId, message: 'Build started' });

    // Start the build process asynchronously
    startBuild(buildId, buildDir, buildType);

  } catch (error) {
    console.error('Upload error:', error);
    res.status(500).json({ error: 'Failed to process upload' });
  }
});

app.get('/download/:buildId', (req, res) => {
  const { buildId } = req.params;
  const buildType = req.query.buildType || 'dev';
  const isUnsigned = req.query.unsigned === 'true';
  let apkName = buildType === 'prod' ? 'app-release.apk' : 'app-debug.apk';
  
  if (buildType === 'prod' && isUnsigned) {
    apkName = 'app-release-unsigned.apk';
  }

  const apkDir = buildType === 'prod' ? 'release' : 'debug';
  
  const apkPath = path.join(
    __dirname, 
    'uploads', 
    buildId, 
    'android', 
    'app', 
    'build', 
    'outputs', 
    'apk', 
    apkDir, 
    apkName
  );

  if (fs.existsSync(apkPath)) {
    res.download(apkPath, `app-${buildType}-${buildId}.apk`);
  } else {
    res.status(404).json({ error: 'APK not found. Build might have failed or is still in progress.' });
  }
});

function emitLog(buildId, message) {
  io.to(buildId).emit('log', message);
  console.log(`[${buildId}] ${message}`);
}

async function startBuild(buildId, buildDir, buildType) {
  try {
    emitLog(buildId, `Starting build ${buildId} (Type: ${buildType})`);
    
    // Check if package.json exists in root or a subdirectory
    let projectDir = buildDir;
    const files = fs.readdirSync(buildDir);
    if (!files.includes('package.json')) {
      // Find the first directory that has package.json (in case of nested zip)
      const subdirs = files.filter(f => fs.statSync(path.join(buildDir, f)).isDirectory());
      for (const dir of subdirs) {
        if (fs.existsSync(path.join(buildDir, dir, 'package.json'))) {
          projectDir = path.join(buildDir, dir);
          break;
        }
      }
    }

    emitLog(buildId, `Project directory: ${projectDir}`);

    // Step 1: Install dependencies
    await runCommand('pnpm', ['install'], projectDir, buildId);

    // Step 2: Expo prebuild
    emitLog(buildId, 'Running expo prebuild...');
    await runCommand('npx', ['expo', 'prebuild', '-p', 'android', '--clean'], projectDir, buildId);

    // Step 3: Gradle build
    const androidDir = path.join(projectDir, 'android');
    if (!fs.existsSync(androidDir)) {
      throw new Error('Android directory not generated by prebuild');
    }

    // Ensure gradlew is executable
    fs.chmodSync(path.join(androidDir, 'gradlew'), '755');

    const gradleTask = buildType === 'prod' ? 'assembleRelease' : 'assembleDebug';
    emitLog(buildId, `Running gradle ${gradleTask}...`);
    await runCommand('./gradlew', [gradleTask], androidDir, buildId);

    // Step 4: Locate APK and notify success
    const apkDirName = buildType === 'prod' ? 'release' : 'debug';
    let apkFileName = buildType === 'prod' ? 'app-release.apk' : 'app-debug.apk';
    let apkPath = path.join(androidDir, 'app', 'build', 'outputs', 'apk', apkDirName, apkFileName);

    // Fallback for unsigned release APKs
    if (buildType === 'prod' && !fs.existsSync(apkPath)) {
      apkFileName = 'app-release-unsigned.apk';
      apkPath = path.join(androidDir, 'app', 'build', 'outputs', 'apk', apkDirName, apkFileName);
    }

    if (fs.existsSync(apkPath)) {
      emitLog(buildId, 'Build completed successfully!');
      io.to(buildId).emit('build_complete', { 
        status: 'success', 
        downloadUrl: `/download/${buildId}?buildType=${buildType}&unsigned=${apkFileName.includes('unsigned')}` 
      });
    } else {
      throw new Error(`APK not found at ${apkPath}`);
    }

  } catch (error) {
    emitLog(buildId, `Build failed: ${error.message}`);
    io.to(buildId).emit('build_complete', { status: 'error', message: error.message });
  }
}

function runCommand(command, args, cwd, buildId) {
  return new Promise((resolve, reject) => {
    emitLog(buildId, `> ${command} ${args.join(' ')}`);
    const child = spawn(command, args, { cwd, shell: true });

    child.stdout.on('data', (data) => {
      emitLog(buildId, data.toString());
    });

    child.stderr.on('data', (data) => {
      emitLog(buildId, data.toString());
    });

    child.on('close', (code) => {
      if (code === 0) {
        resolve();
      } else {
        reject(new Error(`Command ${command} exited with code ${code}`));
      }
    });
    
    child.on('error', (err) => {
      reject(err);
    });
  });
}

const PORT = process.env.PORT || 3000;
server.listen(PORT, () => {
  console.log(`Server listening on port ${PORT}`);
});
